### ISSUE TITLE
Error occurs while buildout

### ISSUE THREAD

**Issue by pabo3000** [reinout/z3c.recipe.usercrontab#7] opened 2015-12-08 16:01 UTC
After rerunning buildout since long time I got the following error. If I pin z3c.recipe.usercrontab = 1.3 everything works fine.

```
Picked: z3c.recipe.usercrontab = 1.4
While:
  Installing.
  Getting section crontab.
  Initializing section crontab.
  Loading zc.buildout recipe entry z3c.recipe.usercrontab:default.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "eggcache/zc.buildout-1.7.1-py2.7.egg/zc/buildout/buildout.py", line 1866, in main
    getattr(buildout, command)(args)
  File "eggcache/zc.buildout-1.7.1-py2.7.egg/zc/buildout/buildout.py", line 509, in install
    [self[part]['recipe'] for part in install_parts]
  File "eggcache/zc.buildout-1.7.1-py2.7.egg/zc/buildout/buildout.py", line 1104, in __getitem__
    options._initialize()
  File "eggcache/zc.buildout-1.7.1-py2.7.egg/zc/buildout/buildout.py", line 1189, in _initialize
    recipe_class = _install_and_load(reqs, 'zc.buildout', entry, buildout)
  File "eggcache/zc.buildout-1.7.1-py2.7.egg/zc/buildout/buildout.py", line 1149, in _install_and_load
    req.project_name, group, entry)
  File "eggcache/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 318, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "eggcache/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 2221, in load_entry_point
    return ep.load()
  File "eggcache/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 1954, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "eggcache/z3c.recipe.usercrontab-1.4-py2.7.egg/z3c/recipe/usercrontab/__init__.py", line 12, in <module>
    from zc.buildout.buildout import bool_option
ImportError: cannot import name bool_option
```

**Comment by reinout** [comment] 2015-12-08 20:14
Duplicate of #6. zc.buildout 1.7 is very old. If you still use it you'll have to stick with usercrontab 1.3. Upgrading to buildout 2.5.0 is really recommended, btw!

**Closed as completed by reinout** 2015-12-08 20:14 UTC
